import { ReactQueryProvider } from './ReactQueryProvider'
import './globals.css'
import { Inter } from 'next/font/google'
import { ReactProvider } from './redux-toolkit/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={inter.className}>
          <ReactProvider>
            {children}
          </ReactProvider>
        </body>
      </html>
    </ReactQueryProvider>
  )
}
